# Generated by Django 5.0 on 2025-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='symbol_icon',
            field=models.ImageField(blank=True, help_text='Icona simbolo personalizzata', upload_to='symbol_icons/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Numero di visualizzazioni della foto'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Icona del profilo utente', upload_to='site_icons/'),
        ),
    ]
