# Generated by Django 5.0 on 2025-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogsettings_symbol_icon_photo_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/'),
        ),
    ]
